/* 策略方案正文：预览只使用这一份连续文档，不改研究记录。 */
(function(global){
'use strict';
const h=value=>String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const stateLabels={pending:'待检查',confirmed:'已确认',discarded:'已放弃',review:'需复查'};
const adoptionLabels={candidate:'可承接候选',limited:'有条件承接',excluded:'不由产品承接',pending:'待论证'};
const appraisalLabels={satisfied:'满足',partial:'部分满足',unsatisfied:'不满足',insufficient:'证据不足'};
const present=value=>typeof value==='string'&&value.trim()?value:'尚未填写';
const fields=rows=>'<dl class="export-record-fields">'+rows.map(([label,value])=>'<div><dt>'+h(label)+'</dt><dd>'+h(present(value))+'</dd></div>').join('')+'</dl>';
const status=(value,flags=[])=>{const recheck=Array.isArray(flags)&&flags.length>0||value==='review';return '<span class="export-status '+(recheck?'needs-review':value==='confirmed'?'confirmed':'')+'">'+h(recheck?'需复查':stateLabels[value]||'待检查')+'</span>';};
const heading=(number,title)=>'<header class="export-section-heading"><span class="export-section-number">'+h(number)+'</span><h2>'+h(title)+'</h2></header>';
const section=(number,title,body,extra='')=>'<section class="export-section '+extra+'" aria-label="'+h(title)+'">'+heading(number,title)+body+'</section>';
const references=ids=>ids.length?ids.map(h).join('、'):'尚无可追溯来源';
const recordHead=(id,title,state,flags)=>'<header class="export-record-heading"><span class="export-record-id">'+h(id)+'</span><h3>'+h(title)+'</h3>'+status(state,flags)+'</header>';
function render(model,options={}){
 const project=model.project||{},totals=model.totals||{},events=model.events||[],patterns=model.patterns||[],directions=model.directions||[],unresolved=model.unresolvedSelections||[];
 const counts=[[totals.measureCount||0,'已选具体措施'],[totals.directionCount||0,'设计方向'],[totals.patternCount||0,'来源评价模式'],[totals.eventCount||0,'相关情感事件']];
 const cover='<header class="export-cover"><p class="export-kicker">DESIGN STRATEGY / 策略方案</p><h2 class="export-title">'+h(present(project.name))+'</h2><p class="export-subtitle">从情感研究依据到具体设计措施</p><p class="export-origin-line">'+h(options.demo?'演示资料 · 方案草案':'方案草案')+(options.date?' · '+h(options.date):'')+'</p><div class="export-summary-metrics">'+counts.map(([count,label])=>'<div><strong>'+count+'</strong><span>'+h(label)+'</span></div>').join('')+'</div></header>';
 const brief=section('01','任务界定',fields([['项目名称',project.name],['目标用户',project.targetUsers],['目标产品',project.product],['目标情感体验',project.emotion],...(project.notes?[['任务备注',project.notes]]:[])]),'export-brief');
 let body='';
 if(directions.length){
  body+=section('02','情感事件','<p class="export-origin-line">以下仅列出被选措施所涉及维度的支持事件，共同来源合并列示。</p>'+events.map(event=>'<article class="export-source-record" data-export-event="'+h(event.id)+'">'+recordHead(event.id,event.displayTitle||event.title,event.eventStatus,event.reviewFlags)+fields([['事件概述',event.title],['事件介绍',event.context],['诱发对象 / 事件',event.trigger],['用户反应',event.response],['情感表达',event.emotionEvidence],['情感分组',event.emotionCategory]])+'<p class="export-origin-line">资料索引：'+h(event.sourceId||'未关联')+(event.paragraphId?' · 段落 '+h(event.paragraphId):'')+'</p></article>').join(''));
  body+=section('03','原因解释',events.map(event=>{const cause=event.cause||{};return '<article class="export-source-record" data-export-cause="'+h(event.id)+'">'+recordHead(event.id,cause.title||'原因解释',cause.status,cause.reviewFlags)+'<p class="export-origin-line">对应情感事件：'+h(event.id)+' · '+h(event.displayTitle||event.title)+'</p>'+fields([['候选原因',cause.reason],['评价对象',cause.evaluationObject],['用户关切',cause.userConcern]])+(cause.appraisals?.length?'<dl class="export-relations">'+cause.appraisals.map(appraisal=>'<div><dt>'+h(appraisal.label)+' · '+h(appraisalLabels[appraisal.status]||'证据不足')+'</dt><dd>'+h(appraisal.judgment)+'</dd></div>').join('')+'</dl>':'')+'</article>';}).join(''));
  body+=section('04','评价模式',patterns.map(pattern=>'<article class="export-pattern" data-export-pattern="'+h(pattern.id)+'">'+recordHead(references(pattern.recordIds||[pattern.id]),pattern.title,pattern.status,pattern.reviewFlags)+'<p>'+h(pattern.summary?.headline||'当前模式尚未形成总结。')+'</p><dl class="export-relations">'+(pattern.summary?.relations||[]).map(relation=>'<div><dt>'+h(relation.label)+' · '+relation.count+' / '+relation.denominator+'</dt><dd>'+h(relation.text)+'</dd></div>').join('')+'</dl><p class="export-origin-line">'+h(pattern.summary?.note||'')+'</p><p class="export-origin-line">本方案涉及的支持事件：'+references(pattern.supportingEventIds||[])+'。模式统计保留当前同情感组的全部 '+(pattern.currentEligibleCount||0)+' 条事件作为分母。</p></article>').join(''));
  body+=section('05','设计转译',directions.map(direction=>'<article class="export-direction" data-export-translation="'+h(direction.id)+'"><header class="export-direction-heading"><span class="export-record-id">'+h(direction.id)+'</span><h3>'+h(direction.title)+'</h3>'+status(direction.status,direction.reviewFlags)+'</header><p class="export-origin-line">来源评价模式：'+h(direction.sourcePatternId)+' · '+h(patterns.find(pattern=>pattern.groupId===direction.groupId)?.title||'')+'</p>'+direction.dimensions.map(dimension=>'<h4 class="export-dimension-label">'+h(dimension.label)+' · '+h(adoptionLabels[dimension.adoption]||'待论证')+'</h4><div class="export-property"><h4>产品需要具备的性质</h4>'+dimension.properties.map(property=>'<p>'+h(property.text)+'</p>').join('')+'</div>'+fields([['产品能力',dimension.capability],...(dimension.boundary?[['能力边界',dimension.boundary]]:[])])+'<p class="export-origin-line">支持事件：'+references(dimension.sourceEventIds||[])+'</p>').join('')+(direction.assumptions?'<div class="export-property"><h4>转译假设 · 需要在目标任务中核对</h4><p>'+h(direction.assumptions)+'</p></div>':'')+'</article>').join(''));
  body+=section('06','已选具体设计措施',directions.map(direction=>'<article class="export-direction" data-export-measures="'+h(direction.id)+'"><header class="export-direction-heading"><span class="export-record-id">'+h(direction.id)+'</span><h3>'+h(direction.title)+'</h3></header>'+direction.dimensions.map(dimension=>'<h4 class="export-dimension-label">'+h(dimension.label)+'</h4>'+dimension.properties.map(property=>'<div class="export-property" data-export-property="'+h(property.key)+'"><h4>产品性质</h4><p>'+h(property.text)+'</p><ol class="export-measure-list">'+property.measures.map(measure=>'<li class="export-measure-item" data-export-measure="'+h(measure.id)+'"><p>'+h(measure.measureText)+'</p><small>'+h(measure.id)+' · '+h(direction.id)+' → '+h(direction.sourcePatternId)+' → '+references(dimension.sourceEventIds||[])+'</small></li>').join('')+'</ol></div>').join('')).join('')+'</article>').join(''));
 }else body+='<section class="export-empty"><h3>还没有可整理的有效措施</h3><p>返回策略比较选择具体措施后，这里会呈现相应研究依据与设计方案。</p></section>';
 if(unresolved.length)body+=section('附录','待核对的选择','<p>以下选择保留原文。对应性质或来源已变化，暂未纳入当前有效方案。</p>'+unresolved.map(item=>{const original=item.snapshot||item;return '<article class="export-unresolved" data-export-unresolved="'+h(original.measureId)+'"><h3>'+h(original.measureId||'措施记录')+' · '+h(original.directionId||'方向未找到')+'</h3><p>'+h(original.measureText)+'</p>'+fields([['原产品性质',original.propertyText],['原评价维度',global.PrototypeAppraisals?.dimensions.find(dimension=>dimension.key===original.dimensionKey)?.label||original.dimensionKey],['需要核对',item.reason]])+'</article>';}).join(''));
 const finish='<footer class="export-finish"><p>本方案按当前保存的任务与所选措施整理。重复来源合并列示，列示内容保留完整文字。</p><p>选择设计措施不改变研究审核状态；候选解释、待检查模式与转译假设仍需核对。</p></footer>';
 return '<article class="export-document" aria-label="策略方案正文">'+cover+brief+body+finish+'</article>';
}
global.PrototypeExportView=Object.freeze({render});
})(window);
